name = "Roassal"
uuid = "5c622eaa-d7fb-4330-9e95-5d9c17cee8d6"
authors = ["Alexandre Bergel <alexandre.bergel@me.com> and contributors"]
version = "0.1.0"

[deps]
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
